### ISSUE TITLE
git lfs fetch with batch on hangs indefinitely

### ISSUE THREAD

**Issue by WillHipschman** [github/git-lfs#593]
Repro steps:

* Remove smudge filter and turn on batch and concurrent transfer:

[filter "lfs"]
       clean = git-lfs clean %f
[lfs]
       batch = true
       concurrenttransfers = 4

* Clone an existing repo
* run "git lfs fetch"

Expected: All pointers are fetched/populated
Actual: cmd shows status: "(0 of 199 files) 0 B / 577.44 MB" indefinitely

**Comment by technoweenie** [comment]
What commit are you on? I think this was fixed a week or so ago.

Also, the smudge filter should have no effect on the fetch command.

**Comment by WillHipschman** [comment]
It's from ~2 weeks ago. I'll sync and try it again :)

**Comment by WillHipschman** [comment]
I'm still seeing it with the latest commit:

commit 4457d7c7c5906025f753579f67f975792235b717

**Comment by technoweenie** [comment]
What does `GIT_TRACE=1 git lfs fetch` show?

**Comment by WillHipschman** [comment]
trace git-lfs: run_command: 'git' rev-parse HEAD
trace git-lfs: run_command: git rev-list --objects --do-walk 1bb5d6f454a0c4c390a858c890c547588cfd42b6
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' config -l -f D:\dev\LfsTest8\.git\config
trace git-lfs: tq: starting 4 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 100
trace git-lfs: api: batch 100 files
trace git-lfs: HTTP: POST https://mseng.visualstudio.com/DefaultCollection/Personal/_git/LFSTest.git/info/lfs/objects/batch
trace git-lfs: HTTP: 203
trace git-lfs: api: batch 99 files
trace git-lfs: HTTP: POST https://mseng.visualstudio.com/DefaultCollection/Personal/_git/LFSTest.git/info/lfs/objects/batch
trace git-lfs: HTTP: 203

**Comment by WillHipschman** [comment]
I'm about to debug into the server code--it's possible it's an issue there. But I figured I'd report it until I know for sure.

**Comment by technoweenie** [comment]
HTTP 203 is definitely weird. The [batch API should always return 200](https://github.com/github/git-lfs/blob/master/docs/api/http-v1-batch.md). Course, this means the client should complain about it :)

**Comment by rubyist** [comment]
Yeah, I'm thinking that the WaitGroup doesn't get sufficient Done() calls when these errors occur, causing a hang.

**Comment by rubyist** [comment]
There were a couple things causing the problem, working up a fix in #594

**Comment by rubyist** [comment]
This has been merged in, thanks for the report!
